name: Build, Test and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
        source-url: https://nuget.pkg.github.com/lucassklp/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        cd Dijkstra.Algorithm
        dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test

    - name: Pack
      run: |  
          cd Dijkstra.Algorithm
          dotnet pack -c Release -o out  
    
    - name: Publish Dijkstra.Algorithm to nuget.org
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: Dijkstra.Algorithm/Dijkstra.Algorithm.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

